#!/bin/sh
#Script dedicado a la busqueda en google ya para buscar imagenes o consultas generales
#Para un mejor funcionamiento se recomienda mover el archivo a "/usr/bin", si tiene problemas al moverlo intente siendo un usuario root
echo -n "Desea buscar imagenes o hacer una consulta? \n"
read RES
if [ $RES = "imagenes" ]; then
    echo -n "Que desea buscar? \n"
    read TERM
    gnome-www-browser "https://www.google.com.co/search?site=imghp&tbm=isch&q=$TERM"
else
    echo -n "Que desea buscar? \n"
    read CONS
    gnome-www-browser "http://google.com/search?q=$CONS"
fi
