#!/bin/bash
FILE="/tmp/out.$$"
GREP="/bin/grep"
echo "Se recomienda estar conectado a una red de alta velocidad y ser usuario root"
echo -n "Desea continuar? [S,N]: "
read RES

if [ $RES = 'n' ]; then
    echo "Vuelva a intentarlo cuando quiera" 1>&2
    exit 1
else 
    if [ "$(id -u)" != "0" ]; then
	# Make sure only root can run our script
	echo "No posee permisos de root" 1>&2
	exit 1
    else
	sudo apt-get -y install subversion
	sudo apt-get -y install git-core
	sudo apt-get -y install emacs
	sudo apt-get -y install shutter
	sudo apt-get -y install gimp
	sudo apt-get -y install kolourpaint4
	sudo apt-get -y install gdebi
	sudo apt-get -y install vlc
	sudo apt-get -y install gcc
	sudo apt-get -y install g++
	sudo apt-get -y install alex
	sudo apt-get -y install happy
	sudo apt-get -y install cabal-install
	sudo apt-get -y install ghci
	echo -n "Desea instalar LaTeX? [S,N]:"
	read RESLAT
	if [ $RESLAT = 's' ]; then
	    echo "Se tomara un tiempo mientras que se instala LaTeX"
	    sudo apt-get -y install latex*
	fi
	sudo add-apt-repository ppa:webupd8team/sublime-text-3 
	sudo apt-get update 
	sudo apt-get -y install sublime-text-installer

	wget -O dropbox.deb https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_1.6.2_i386.deb
	wget -O google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_i386.deb
	wget -O skype.deb http://www.skype.com/go/getskype-linux-beta-ubuntu-32

	sudo gdebi dropbox.deb
	sudo gdebi google-chrome.deb
	sudo gdebi skype.deb
	rm *.deb
    fi
fi
