#!/bin/bash

if [ "$(id -u)" != "0" ]; then
    echo "No posee permisos de root" 1>&2
    exit 1
else
    sudo apt-get -y update
    sudo apt-get -y upgrade
    sudo apt-get -y build-essentials
    sudo apt-get -y install subversion
    sudo apt-get -y install git-core
    sudo apt-get -y install emacs
    sudo apt-get -y install shutter
    sudo apt-get -y install gimp
    sudo apt-get -y install kolourpaint4
    sudo apt-get -y install gdebi
    sudo apt-get -y install vlc
    sudo apt-get -y install gcc
    sudo apt-get -y install g++
    sudo apt-get -y install dropbox
    sudo apt-get -y install bleachbit
    echo -n "Desea instalar Hazkell? [S,N]:"
    read RESHAS
    if [ $RESHAS = 's' ] || [ $RESHAS = 'S' ]; then
	sudo apt-get -y install alex
	sudo apt-get -y install happy
	sudo apt-get -y install cabal-install
	sudo apt-get -y install ghci
    fi
    echo -n "Desea instalar LaTeX? [S,N]:"
    read RESLAT
    if [ $RESLAT = 's' ] || [ $RESLAT = 'S' ]; then
	echo "Se tomara un tiempo mientras que se instala LaTeX"
	sudo apt-get -y install latex*
    fi
fi
